# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmRmMDk0YmFmZGM1MTAwZGVmZTM4ZmI2NjE0ZGVkMzM2NWUxNjkxZTgyYzViMTZkMmFiNThmOTg1NTk5YWVmNTdjYzBlNGI0ZjM1YzEyZWQ2YmZmOTJhMWMzODA2MzEzYmMwZjI0YmYyOTUxYWFiOTAyNjY1YTU1M2NlMTQyOTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
